### ISSUE TITLE
weird cop labelling

### ISSUE THREAD

**Issue by tlynn747** [fosterjen/Irish-Universal-Dependency-Treebank#22]
Possible bug in a script..

While working through the progressive aspectual phrases, I've come across the random labelling of 'cop' on tokens that aren't copulas...

e.g. bíodh nach sos dó ach ag(cop) mealladh 

Need to review all copula labels to make sure they are only Copulas.

**Comment by fosterjen** [comment]
I found this bug. It was happening when there was more than one xcomp dependent on the copula. I marked all the cases and checked them in the latest version of the file. 

I made changes to the following cases: 2558, 2606, 4168, 5823, 6348, 7352, 7374, 8585, 13065, 13693, 17638,  18989, 19668?, 20245, 20349, 20371, 21041, 21501, 21522, 21721, 22132, 24484

I have a question mark for line number #19668. I wasn't sure about the relation "nsubj" here.
