### ISSUE TITLE
wrongly attached dependents of punctuation

### ISSUE THREAD

**Issue by tlynn747** [fosterjen/Irish-Universal-Dependency-Treebank#24]
Have come across a few instances where tokens are randomly attached to internal punctuation..??

e.g. Chogadh Mhóir *,* chun tuiscint a *bheith* ag riarthóir

Need to review the entire file for this...

**Comment by fosterjen** [comment]
The new version of the script was assuming that preps were attached to nmods and it breaks when the prep is also attached to internal punctuation. Will fix the code and update the data manually.

**Comment by tlynn747** [comment]
Found an example of weird punctuation attachment. When all is fixed, look out for this one:
The second comma should be attached to 13, not 3 - and gCoimisiún shouldn't be attached to punctuation, but déanta.

1	Tá	bí	VERB	VERB	_	0	root	_	_
2	gearán	gearán	NOUN	NOUN	_	1	nsubj	_	_
3	déanta	déanta	ADJ	ADJ	_	1	xcomp:pred	_	_
4	ag	ag	ADP	ADP	_	5	case	_	_
5	Unison	Unison	PROPN	PROPN	_	3	nmod	_	_
6	,	,	PUNCT	PUNCT	_	7	punct	_	_
7	ceardchumann	ceardchumann	NOUN	NOUN	_	5	appos	_	_
8	lucht	lucht	NOUN	NOUN	_	7	compound	_	_
9	na	na	DET	DET	_	10	det	_	_
10	mbónaí	bóna	NOUN	NOUN	_	8	compound	_	_
11	bána	bán	ADJ	ADJ	_	10	amod	_	_
12	,	,	PUNCT	PUNCT	_	3	punct	_	_
13	leis	le	ADP	ADP	_	15	case	_	_
14	an	an	DET	DET	_	15	det	_	_
15	gCoimisiún	gcoimisiún	NOUN	NOUN	_	12	nmod	_	_

**Comment by fosterjen** [comment]
This was one of the ones I manually fixed. However, I attached the comma's in these cases to the head of the phrase rather than the case marker. So in this case, it's attached to 15. I hope this is ok? If not we can raise it as an issue to be looked at for the second release.

**Comment by tlynn747** [comment]
Yes you're right about the attachment to gCoimisiún instead of leis. The head of the phrase is correct.
