### ISSUE TITLE
Issues with coordination of prepositional phrases

### ISSUE THREAD

**Issue by tlynn747** [fosterjen/Irish-Universal-Dependency-Treebank#25]
Multiple cases where the preposition (case) is now dependent on the conjoined noun, instead of the first element (noun) of the conjoined phrase.

e.g. ag plé *le* scrúdaithe agus le *trialacha* cainte

**Comment by fosterjen** [comment]
This is another instance of the same bug with the processPP method. Will update the code and fix manually.

**Comment by fosterjen** [comment]
Here is a list of all the preposition cases that were affected by this bug and which have been manually fixed. Those with a question mark are those I'm not sure about.

108, 236, 493, 694, 766, 1018, 1108, 1122, 1322, 1341, 1370, 1392, 1456, 1478, 1578, 1591?, 1672, 1729, 1907, 1947, 2206, 2277, 2316, 2336, 2381, 2424, 2436, 2550, 2631,2754, 3050, 3102, 3186, 3253, 3336, 3502, 3531, 3637, 3869, 4137, 4284, 4295, 4302, 4319, 4593, 4749, 4799, 5026, 5029, 5197, 5198, 5331, 5332, 5400, 5402, 5571, 5574, 5899, 5991, 6009, 6041, 6043, 6119, 6165, 6187, 6192, 6195, 6198, 6281, 6300, 6632, 6651, 6628, 7076, 7187, 7226, 7257, 7354, 7398, 7610, 7639, 7920?, 8027, 8114,8207, 8393, 8457?, 8543, 8547, 8693, 8702, 8858, 9066, 9099, 9178, 9274, 9351, 9709, 9760, 9823, 9951, 10013, 10256, 10261, 10390, 10587, 10686, 10747, 10770, 10852?, 11014, 11017, 11056, 11107, 11164, 11200, 11241, 11271, 11283, 11649, 11705, 11719, 11772,
11813, 12013, 12045, 12137, 12138, 12199, 12255, 12264, 12284,12329, 12354, 12488?,12489?, 12532, 12539, 12620, 12701?,12702?, 12740, 12765, 13053, 13054, 13091, 13142, 13171, 13233,
13340, 13355, 13358, 13393, 13395, 13579, 13625, 13627, 13641, 13643, 13770, 13814?, 13185?, 14073, 14192,14195, 14625, 14763, 14837, 14858, 15004, 15034, 15056, 15150, 15176, 15325, 15334, 15350?, 15351, 15431, 15463, 15491, 15754, 15758, 15804, 15907, 15912, 16084, 16241, 16316, 16332, 16338, 16445, 16566, 17064, 17073, 17130, 17133, 17135, 17204, 17219, 17255, 17295, 17588,17727, 17737, 17865, 17919, 17923, 17929, 17972, 18098, 18177, 18207?, 18231?, 18320?, 18353?, 18372?, 18391?, 18408?, 18539, 18558, 18563?, 18581?, 18614?, 18628?, 18705, 18800, 18848, 19139, 19184, 19427, 19463, 19518, 19785 (?aimsir), 19842?, 19846?, 19916, 19977, 20019, 20049??, 20092, 20207?, 20221,20321, 20455, 20587, 20607, 20718, 21066, 21183, 21236?, 21250, 21258, 21373, 21507, 21699,21700, 21890, 21920?,21921?, 22107, 22372, 22524?,22525?, 22615, 22638, 22681, 22684, 22804?,22836, 22839, 22848, 23221, 23380, 23490, 23553?, 23584, 23609,23782, 23917, 24106, 24108, 24156, 24390

**Comment by tlynn747** [comment]
Reviewed and fixed some ?-marked cases.
